Exception in connection handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/websockets/server.py", line 78, in handler
    yield from self.ws_handler(self, path)
  File "server/main.py", line 479, in handler
    await websocket.send(json.dumps(provide_active_sessions()))
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
TypeError: keys must be a string
Exception in connection handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/websockets/server.py", line 78, in handler
    yield from self.ws_handler(self, path)
  File "server/main.py", line 477, in handler
    logged_in_users += 1
UnboundLocalError: local variable 'logged_in_users' referenced before assignment
Exception in connection handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/websockets/server.py", line 78, in handler
    yield from self.ws_handler(self, path)
  File "server/main.py", line 477, in handler
    logged_in_users += 1
UnboundLocalError: local variable 'logged_in_users' referenced before assignment
Exception in connection handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/websockets/server.py", line 78, in handler
    yield from self.ws_handler(self, path)
  File "server/main.py", line 479, in handler
    await websocket.send(json.dumps(provide_active_sessions()))
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
TypeError: keys must be a string
